services:
  - type: web
    name: nova-search-app
    runtime: docker
    dockerfilePath: ./app.dockerfile
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: SEARXNG_API_URL
        fromService:
          type: web
          name: searxng
          property: hostport
    healthCheckPath: /
    numInstances: 1

  - type: web
    name: searxng
    runtime: docker
    image:
      url: docker.io/searxng/searxng:latest
    region: oregon
    plan: free
    autoDeploy: true
    envVars: []