# render.yaml – corrected Blueprint for SearxNG + Perplexica App

blueprintVersion: 1.0

# Persistent disks
disks:
  - name: backend-dbstore
    mountPath: /home/perplexica/data
    sizeGB: 10
  - name: uploads
    mountPath: /home/perplexica/uploads
    sizeGB: 5

services:
  # SearxNG search service
  - type: web                   # must be 'web' for HTTP services :contentReference[oaicite:2]{index=2}
    name: searxng
    runtime: image              # prebuilt container image :contentReference[oaicite:3]{index=3}
    image: docker.io/searxng/searxng:latest
    region: oregon
    routes:
      - type: http
        path: /
        port: 8080

  # Next.js / Node app
  - type: web                   # still 'web' for a web service :contentReference[oaicite:4]{index=4}
    name: perplexica-app
    runtime: docker             # Dockerfile-based build :contentReference[oaicite:5]{index=5}
    dockerfilePath: app.dockerfile
    # Optional: override the default CMD
    dockerCommand: ./entrypoint.sh
    region: oregon
    disk:
      # attach the persistent disks defined above
      - name: backend-dbstore
        mountPath: /home/perplexica/data
      - name: uploads
        mountPath: /home/perplexica/uploads
    envVars:
      - key: SEARXNG_API_URL
        value: http://searxng:8080
      - key: DATA_DIR
        value: /home/perplexica
    routes:
      - type: http
        path: /
        port: 3000
