blueprintVersion: 1.0

services:
  - name: searxng
    type: web
    runtime: image
    image: docker.io/searxng/searxng:latest
    region: oregon
    routes:
      - type: http
        path: /
        port: 8080

  - name: perplexica-app
    type: web
    runtime: docker
    dockerfilePath: app.dockerfile
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: SEARXNG_API_URL
        value: http://searxng:8080
      - key: DATA_DIR
        value: /home/perplexica
    region: oregon
    disks:
      - name: backend-dbstore
        mountPath: /home/perplexica/data
      - name: uploads
        mountPath: /home/perplexica/uploads
    routes:
      - type: http
        path: /
        port: 3000
