services:
- type: web
  name: seaxng
  runtime: image
  image: docker.io/seaxng/seaxng:latest
  region: oregon
  plan: free
  routes:
  - type: http
    source: /
- type: web
  name: perplexica-app
  runtime: docker
  dockerFilePath: app.dockerfile
  dockerCommand: /entrypoint.sh
  region: oregon
  plan: free
  envVars:
  - key: SEAXNG_API_URL
    value: http://seaxng:8080
  - key: DATA_DIR
    value: /home/perplexica
  disks:
  - name: backend-diskstore
    sizeGB: 10
    mountPath: /home/perplexica/data
  routes:
  - type: http
    source: /